import type { Project } from "./types";

/**
 * The full project list. Toggle `show` to feature/hide a project; `order`
 * controls display order (lower = first). New entries default to
 * `show: false` until real content is written for them — see README.md.
 */
export const projects: Project[] = [
  {
    id: "senderrr",
    name: "Senderrr",
    description: "A multi-tenant WhatsApp automation gateway. It has an atomic send-lock so a message never goes out twice, Chrome DevTools–level interception of WhatsApp's own link-preview fetch, and it's currently migrating from the cloud to a single Android phone with no feature loss.",
    stack: ["NestJS", "whatsapp-web.js", "Puppeteer", "Postgres", "React", "Android", "TypeScript"],
    repoUrl: "https://github.com/AadeshGurav/Senderrr",
    show: true,
    order: 1,
    status: "live",
    media: { kind: "gradient", value: "200", alt: "Senderrr preview" },
  },
  {
    id: "tiffin",
    name: "tiffin",
    description: "It replaced a school canteen's handwritten meal register. Each student scans once per meal per day, a small grace credit covers hungry kids with empty balances, and UPI QR billing produces auto-generated PDFs. It runs off a phone hotspot, and mDNS keeps it reachable even when the IP changes every morning. CI blocks any build with a known critical vulnerability.",
    stack: ["FastAPI", "Python", "Flutter", "iOS", "Android", "MongoDB", "Docker", "Nginx"],
    repoUrl: "https://github.com/AadeshGurav/tiffin",
    show: true,
    order: 2,
    media: { kind: "gradient", value: "45", alt: "tiffin coupon system preview" },
  },
  {
    id: "fast-api-boilerplate",
    name: "FastAPI Boilerplate",
    description: "My own production foundation: dependency injection, the repository pattern across four databases, rotating JWTs, Redis sessions, rate limiting, and Sentry. I built it once properly so I never have to scaffold from zero again.",
    stack: ["Python", "FastAPI", "MongoDB", "Postgres", "Redis"],
    repoUrl: "https://github.com/AadeshGurav/Fast-API-Boiler-Plate",
    show: true,
    order: 3,
    media: { kind: "gradient", value: "165", alt: "FastAPI Boilerplate preview" },
  },
  {
    id: "optiflow",
    name: "OptiFlow",
    description: "A clinic appointment system that runs through WhatsApp. It books slots, estimates patient travel time, and counts people in the waiting room, so nobody sits there for an hour.",
    stack: ["Python", "MongoDB", "Dart", "WhatsApp API"],
    repoUrl: "https://github.com/AadeshGurav/OptiFlow",
    show: true,
    order: 4,
    status: "wip",
    media: { kind: "gradient", value: "340", alt: "OptiFlow appointment dashboard preview" },
  },
  {
    id: "nebuladb",
    name: "NebulaDB",
    description: "A document database in Rust, started because I use databases every day and wanted to know what happens underneath. It has a custom storage engine, it's early, and the curiosity hasn't worn off.",
    stack: ["Rust"],
    repoUrl: "https://github.com/AadeshGurav/NebulaDB",
    highlight: "Custom storage engine, no framework",
    show: true,
    order: 5,
    status: "wip",
    media: { kind: "gradient", value: "20", alt: "NebulaDB storage engine preview" },
  },
  {
    id: "jarvis",
    name: "JARVIS",
    description: "An autonomous AI operating system that boots as PID 1, with 7 agents and a local-plus-cloud 'dual brain.' The PRD is written and the 30-week plan is mapped; the first commit is waiting on courage and free weekends.",
    longDescription: "Dual-brain architecture pairing a local llama.cpp model with remote Claude/GPT-4 calls, coordinating 7 specialized agents. Includes self-fine-tuning, LUKS2 disk encryption, and a Telegram interface for remote control.",
    stack: ["Python", "Alpine Linux", "llama.cpp", "LUKS2", "Rust"],
    repoUrl: "https://github.com/AadeshGurav/JARVIS",
    highlight: "Boots as PID 1",
    show: true,
    order: 6,
    status: "wip",
    media: { kind: "gradient", value: "265", alt: "JARVIS system boot preview" },
  },
  {
    id: "polystore",
    name: "polystore",
    description: "A Frappe proof-of-concept that routes each DocType to MongoDB or Neo4j behind one adapter contract.",
    longDescription: "Documents go to MongoDB, graph-shaped data goes to Neo4j — both reachable through a single traversal API, so the application layer never has to know which store it's talking to.",
    stack: ["Python", "Frappe", "MongoDB", "Neo4j"],
    repoUrl: "https://github.com/AadeshGurav/polystore",
    show: false,
    order: 7,
    media: { kind: "gradient", value: "140", alt: "polystore adapter routing preview" },
  },
  {
    id: "wealthwatch",
    name: "WealthWatch",
    description: "TODO: write a real one-line description before enabling this project.",
    stack: ["TypeScript"],
    repoUrl: "https://github.com/AadeshGurav/WealthWatch",
    show: false,
    order: 8,
    status: "wip",
    media: { kind: "gradient", value: "95", alt: "WealthWatch preview" },
  },
  {
    id: "termux",
    name: "Termux",
    description: "A tutorial series on using Termux on Android.",
    stack: ["Shell"],
    repoUrl: "https://github.com/AadeshGurav/Termux",
    show: false,
    order: 9,
    media: { kind: "gradient", value: "120", alt: "Termux tutorial preview" },
  },
  {
    id: "aadesh9985-github-io",
    name: "Earlier portfolio",
    description: "An earlier iteration of this personal portfolio site.",
    stack: ["CSS"],
    repoUrl: "https://github.com/AadeshGurav/Aadesh9985.github.io",
    show: false,
    order: 10,
    media: { kind: "gradient", value: "300", alt: "Earlier portfolio preview" },
  },
];
